version: '3.8'

services:
  db:
    container_name: exams_db
    image: postgres:13.4-alpine
    restart: always
    user: postgres  # importante definir o usuário
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres  # senha padrão
      - POSTGRES_USER=postgres  # usuário padrão
      - POSTGRES_DB=db  # necessário porque foi configurado assim no settings
    ports:
      - 5433:5432  # repare na porta externa 5433
    networks:
      - exams

  redis:
    container_name: exams_redis
    image: 'redis:alpine'
    hostname: redis
    networks:
      - exams

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exams_app
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env:/app/.env
      - /tmp:/tmp
    command: bash -c "gunicorn backend.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - redis
      - db
    networks:
      - exams

  nginx:
    container_name: exams_nginx
    image: nginx
    hostname: nginx
    ports:
      - '8001:8000'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - exams

  pgadmin:
    container_name: exams_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - exams

  mailhog:
    container_name: exams_mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - exams

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exams_celery
    command: "celery -A backend worker -l info"
    depends_on:
      - app
      - redis
      - db
    networks:
      - exams

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exams_flower
    environment:
      - FLOWER_PORT=8888
    command: "celery -A backend flower --address=0.0.0.0"
    ports:
      - 8888:8888
    depends_on:
      - celery
    networks:
      - exams

volumes:
  pgdata:  # mesmo nome do volume externo definido na linha 10
  pgadmin:

networks:
  exams:
