# Generated by Django 4.0.4 on 2022-04-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medic',
            new_name='Doctor',
        ),
    ]
